Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2020-07, with the labels that each got.

#82 Modernise emulator
  lewis_emulators/superlogics/device.py
  lewis_emulators/superlogics/interfaces/stream_interface.py
Labels: size/M

#79 Initial emulator
  lewis_emulators/mecfrf/__init__.py
  lewis_emulators/mecfrf/device.py
  lewis_emulators/mecfrf/interfaces/__init__.py
  lewis_emulators/mecfrf/interfaces/stream_interface.py
  lewis_emulators/mecfrf/states.py
Labels: size/L

#83 Ticket5333 helium recovery fins plc
  lewis_emulators/fins/__init__.py
  lewis_emulators/fins/device.py
  lewis_emulators/fins/interfaces/__init__.py
  lewis_emulators/fins/interfaces/response_utilities.py
  lewis_emulators/fins/interfaces/stream_interface.py
  lewis_emulators/fins/states.py
  lewis_emulators/icefrdge/interfaces/stream_interface.py
  lewis_emulators/skf_mb350_chopper/device.py
  lewis_emulators/skf_mb350_chopper/interfaces/stream_interface.py
  lewis_emulators/utils/byte_conversions.py
Labels: size/XL
