Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2020-11, with the labels that each got.

#89 Ticket3185 remote mode reliability
  lewis_emulators/kepco/device.py
  lewis_emulators/kepco/interfaces/__init__.py
  lewis_emulators/kepco/interfaces/kepco.py
Labels: size/M

#91 Ticket 5663: HTS Magnet Smart Monitor
  lewis_emulators/smrtmon/__init__.py
  lewis_emulators/smrtmon/device.py
  lewis_emulators/smrtmon/interfaces/__init__.py
  lewis_emulators/smrtmon/interfaces/stream_interface.py
  lewis_emulators/smrtmon/states.py
Labels: size/M

#74 Ticket5259 switch rates mid ramp
  lewis_emulators/cryogenic_sms/device.py
  lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
  lewis_emulators/cryogenic_sms/states.py
Labels: size/S

#90 Fix setpol cmd
  lewis_emulators/danfysik/device.py
  lewis_emulators/danfysik/interfaces/dfkps_8500.py
  lewis_emulators/danfysik/interfaces/dfkps_base.py
Labels: size/S

#94 Tested branch with this regex but then failed to commit it
  lewis_emulators/danfysik/interfaces/dfkps_base.py
Labels: size/XS
