Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2020-04, with the labels that each got.

#75 Fixed newline for repo checks
  other_emulators/DAQmx/start_sim.bat
  other_emulators/DAQmx/stop_sim.bat
Labels: size/XS

#72 continually add readings into the buffer unless otherwise specified
  lewis_emulators/keithley_2700/device.py
Labels: size/M

#77 Fixed command list and removed logging
  lewis_emulators/lakeshore460/interfaces/stream_interface.py
Labels: size/XS

#69 Ticket 4287 Update rotsc from tests
  lewis_emulators/rotating_sample_changer/device.py
  lewis_emulators/rotating_sample_changer/interfaces/HRPD_stream_interface.py
  lewis_emulators/rotating_sample_changer/interfaces/POLARIS_stream_interface.py
  lewis_emulators/rotating_sample_changer/states.py
Labels: size/M

#68 Add emulator for DMA4500M
  lewis_emulators/dma4500m/__init__.py
  lewis_emulators/dma4500m/device.py
  lewis_emulators/dma4500m/interfaces/__init__.py
  lewis_emulators/dma4500m/interfaces/stream_interface.py
  lewis_emulators/dma4500m/states.py
Labels: size/L

#76 Adjust emulator from hardware
  lewis_emulators/mezflipr/interfaces/stream_interface.py
Labels: size/XS
