Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2020-01, with the labels that each got.

#60 Ticket4926 comission ice fridge
  lewis_emulators/icefrdge/interfaces/stream_interface.py
Labels: size/S

#61 Added cmd for reading last setpoint
  lewis_emulators/danfysik/interfaces/dfkps_base.py
Labels: size/XS

#62 Ticket5042 danfysik changes rework
  lewis_emulators/danfysik/device.py
  lewis_emulators/danfysik/interfaces/dfkps_base.py
Labels: size/M

#63 Add remote mode to emulator
  lewis_emulators/kepco/device.py
  lewis_emulators/kepco/interfaces/stream_interface.py
Labels: size/M

#64 Add emulator property
  lewis_emulators/itc503/device.py
  lewis_emulators/itc503/interfaces/stream_interface.py
Labels: size/S
