Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2021-02, with the labels that each got.

#98 Ticket5950 lksh340 excitation
  lewis_emulators/lakeshore340/device.py
  lewis_emulators/lakeshore340/interfaces/stream_interface.py
Labels: size/S

#101 Fix keithley tests
  lewis_emulators/keithley_2400/interfaces/stream_interface.py
Labels: size/M

#100 Stream interface encodes only strings
  lewis_emulators/attocube_anc350/interfaces/stream_interface.py
  lewis_emulators/fins/interfaces/response_utilities.py
  lewis_emulators/fins/interfaces/stream_interface.py
  lewis_emulators/skf_mb350_chopper/interfaces/crc16.py
  lewis_emulators/skf_mb350_chopper/interfaces/response_utilities.py
  lewis_emulators/skf_mb350_chopper/interfaces/stream_interface.py
  lewis_emulators/utils/byte_conversions.py
Labels: size/L

#102 Fix issue with python 3 keys being iterator
  lewis_emulators/knr1050/device.py
Labels: size/XS

#103 Fix lakeshore 460
  lewis_emulators/lakeshore460/interfaces/stream_interface.py
Labels: size/XS

#105 Fix python 3 errors in mecfrf
  lewis_emulators/mecfrf/interfaces/stream_interface.py
Labels: size/XS
