Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2021-03, with the labels that each got.

#107 Fix keithley 2700
  lewis_emulators/keithley_2700/device.py
  lewis_emulators/keithley_2700/interfaces/stream_interface.py
  lewis_emulators/utils/command_builder.py
Labels: size/M

#106 Ticket5990 - slew rate
  lewis_emulators/danfysik/device.py
  lewis_emulators/danfysik/interfaces/dfkps_8500.py
Labels: size/S

#109 Ticket6202 add ioc afg3021 b
  lewis_emulators/tekafg3XXX/__init__.py
  lewis_emulators/tekafg3XXX/device.py
  lewis_emulators/tekafg3XXX/interfaces/__init__.py
  lewis_emulators/tekafg3XXX/interfaces/stream_interface.py
  lewis_emulators/tekafg3XXX/states.py
Labels: size/M

#110 removing icefrdge
  lewis_emulators/icefrdge/__init__.py
  lewis_emulators/icefrdge/device.py
  lewis_emulators/icefrdge/interfaces/__init__.py
  lewis_emulators/icefrdge/interfaces/stream_interface.py
  lewis_emulators/icefrdge/states.py
Labels: size/XL

#108 Add new emulator hlx503 based on itc503 but with a magic box that allows us to control per control channel
  lewis_emulators/hlx503/__init__.py
  lewis_emulators/hlx503/device.py
  lewis_emulators/hlx503/interfaces/__init__.py
  lewis_emulators/hlx503/interfaces/stream_interface.py
  lewis_emulators/hlx503/states.py
Labels: size/L

#112 fix backdoor issue with afg3xxx
  lewis_emulators/tekafg3XXX/device.py
  lewis_emulators/tekafg3XXX/interfaces/stream_interface.py
Labels: size/XS
