Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2022-08, with the labels that each got.

#148 Fix line endings
  lewis_emulators/cryogenic_sms/__init__.py
  lewis_emulators/cryogenic_sms/device.py
  lewis_emulators/cryogenic_sms/interfaces/__init__.py
  lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
  lewis_emulators/cryogenic_sms/states.py
Labels: size/XL

#149 Add Tripping Functionality to Emulator
  lewis_emulators/ttiplp/device.py
  lewis_emulators/ttiplp/interfaces/stream_interface.py
Labels: size/M

#111 Ticket5993 setup correctly
  lewis_emulators/cryogenic_sms/device.py
  lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
Labels: size/S
