Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2022-09, with the labels that each got.

#152 Ticket7255 fix switching
  lewis_emulators/tpg300/device.py
  lewis_emulators/tpg300/interfaces/stream_interface.py
Labels: size/S

#151 Refactor some lewis emulator files
  lewis_emulators/danfysik/device.py
  lewis_emulators/danfysik/interfaces/dfkps_8000.py
  lewis_emulators/danfysik/interfaces/dfkps_8500.py
  lewis_emulators/danfysik/interfaces/dfkps_8800.py
  lewis_emulators/danfysik/interfaces/dfkps_9X00.py
  lewis_emulators/danfysik/interfaces/dfkps_base.py
  lewis_emulators/edwardstic/device.py
  lewis_emulators/edwardstic/interfaces/stream_interface.py
  lewis_emulators/fzj_dd_fermi_chopper/device.py
  lewis_emulators/fzj_dd_fermi_chopper/interfaces/stream_interface.py
Labels: size/M

#154 Fix phase returning frequency in Tekafg3xxx emulator
  lewis_emulators/tekafg3XXX/interfaces/stream_interface.py
Labels: size/XS

#153 Add second pressure card for concurrent spc tests
  lewis_emulators/mercuryitc/device.py
Labels: size/XS
