Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2023-01, with the labels that each got.

#160 Fix reading of floats
  lewis_emulators/fins/interfaces/response_utilities.py
  lewis_emulators/fins/interfaces/stream_interface.py
Labels: size/S

#159 Ticket7058
  lewis_emulators/superlogics/__init__.py
  lewis_emulators/superlogics/device.py
  lewis_emulators/superlogics/interfaces/__init__.py
  lewis_emulators/superlogics/interfaces/stream_interface.py
  lewis_emulators/superlogics/states.py
Labels: size/L

#158 Instron
  lewis_emulators/instron_stress_rig/interfaces/stream_interface.py
Labels: size/S

#161 Rikenfe rb2 protocol
  lewis_emulators/danfysik/interfaces/dfkps_RIKEN.py
Labels: size/M
