Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2023-08, with the labels that each got.

#163 Ticket6777
  lewis_emulators/eurotherm/device.py
  lewis_emulators/eurotherm/interfaces/modbus_interface.py
Labels: size/L

#171 Emulator changes required for NeedleValve
  lewis_emulators/eurotherm/device.py
  lewis_emulators/eurotherm/interfaces/modbus_interface.py
Labels: size/S

#172 Adding the modbus interface for the 1242
  lewis_emulators/moxa12xx/interfaces/modbus_interface.py
Labels: size/S

#169 Refactor and generalise TPG300 emulator
  lewis_emulators/tpg300/device.py
  lewis_emulators/tpg300/interfaces/__init__.py
  lewis_emulators/tpg300/interfaces/stream_interface.py
  lewis_emulators/tpgx00/__init__.py
  lewis_emulators/tpgx00/device.py
  lewis_emulators/tpgx00/interfaces/__init__.py
  lewis_emulators/tpgx00/interfaces/stream_interface.py
  lewis_emulators/tpgx00/states.py
Labels: size/XXL
