Repository ISISComputingGroup/EPICS-DeviceEmulator, pull requests merged in 2024-05, with the labels that each got.

#175 Ticket8253_make_IOC_work_if_crate_is_power_cycled
  lewis_emulators/mclennan/device.py
  lewis_emulators/mclennan/interfaces/stream_interface.py
Labels: size/M

#176 Remove usage of six
  lewis_emulators/danfysik/interfaces/dfkps_base.py
  lewis_emulators/ips/interfaces/stream_interface.py
  lewis_emulators/kepco/interfaces/kepco.py
  lewis_emulators/kynctm3k/device.py
  lewis_emulators/mecfrf/interfaces/stream_interface.py
  lewis_emulators/mkspr4kb/interfaces/stream_interface.py
  lewis_emulators/tpgx6x/interfaces/stream_interface.py
Labels: size/S

#173 Use just LF for in terminator
  lewis_emulators/kepco/interfaces/kepco.py
Labels: size/XS
